version: 2.1

# Docker defaults
defaults: &defaults
  docker:
    - image: cimg/node:18.16.1
  working_directory: /mnt/ramdisk/repo

# Jobs
jobs:
  install-deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
  lint-test-and-build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Lint code
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Build everything including docs
          command: yarn ci:build

# Workflows
workflows:
  version: 2
  build-and-test:
    jobs:
      - install-deps
      - lint-test-and-build
