# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

defaults: &defaults
  docker: # Choose the version of Node you want here
    - image: cimg/node:18.16.1
  working_directory: /mnt/ramdisk/repo

version: 2.1

orbs: node:circleci/node@5.1.0

jobs:
  face-detection-tests:
    <<: *defaults
    resource_class: large
    steps:
      - checkout
      - common-install-deps
      - run: # We don't want to install CocoaPods on ubuntu where we run the tests.
          name: Set up dummy `pod` command
          command: |
            sudo ln /bin/true /usr/local/bin/pod
      - run:
          name: Ensure git user is configured
          command: |
            git config --global user.email "ci@infinite.red"
            git config --global user.name "Infinite Red CI"
      - run:
          name: PWD
          command: pwd
      - run:
          name: Run static tests
          command: yarn ci:lint && yarn ci:test
          no_output_timeout: 5m
  face-detection-publish:
    <<: *defaults
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - common-install-deps
      - run:
          name: Build package
          command: yarn build
      # Run semantic-release after all the above is set.
      - run:
          name: Publish to npm
          command: yarn ci:publish # this will be added to your package.json scripts

workflows:
  version: 2
  face-detection-test_and_release:
    jobs:
      - face-detection-tests
      - face-detection-publish:
          context: infinitered-npm-package
          requires:
            - face-detection-tests
          filters:
            branches:
              only: main
